# Generated by Django 3.0.8 on 2020-07-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50, null=True)),
                ('lname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
            ],
            options={
                'verbose_name': 'Birthday',
                'verbose_name_plural': 'Birthdays',
                'managed': True,
            },
        ),
    ]
