# Generated by Django 3.0.8 on 2020-07-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=500)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='birthday',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='fname',
            field=models.CharField(max_length=50, verbose_name='Fisrt name'),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='lname',
            field=models.CharField(max_length=50, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='mname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle name'),
        ),
    ]
