# Generated by Django 3.0.8 on 2020-07-06 01:27

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.TextField(null=True, validators=[user.validators.validate_mobile_number]),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp_number',
            field=models.TextField(null=True, validators=[user.validators.validate_mobile_number]),
        ),
    ]
