# Generated by Django 3.0.8 on 2020-07-06 01:34

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200706_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(max_length=15, null=True, validators=[user.validators.validate_mobile_number]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='whatsapp_number',
            field=models.CharField(max_length=15, null=True, validators=[user.validators.validate_mobile_number]),
        ),
    ]
